In [6]:
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 57.2MB/s]


In [20]:
import matplotlib.image as mpimg
import numpy as np
img = mpimg.imread('/content/dog.jpeg')
gray_img_01 = (np.max(img,axis=2)+np.min(img,axis=2))/2
print(gray_img_01)

gray_img_01[0,0]

[[102.5  73.5  66.5 ...  28.   28.   28. ]
 [103.5  73.5  67.5 ...  27.5  28.   27.5]
 [103.5  74.5  67.5 ...  27.   26.5  26. ]
 ...
 [124.5 104.5  97.  ... 117.  114.  112. ]
 [117.5  97.5  90.5 ... 117.  114.  112.5]
 [115.5  95.5  87.5 ... 119.  116.  114.5]]


102.5

In [22]:
import matplotlib.image as mpimg
import numpy as np
img = mpimg.imread('/content/dog.jpeg')
gray_img_01 = (np.mean(img, axis=2))
print(gray_img_01)

gray_img_01[0,0]

[[107.66666667  78.66666667  71.66666667 ... 154.33333333 154.33333333
  154.33333333]
 [108.66666667  78.66666667  72.66666667 ... 154.         154.33333333
  154.        ]
 [108.66666667  79.66666667  72.66666667 ... 153.66666667 153.
  152.66666667]
 ...
 [131.33333333 111.66666667 104.33333333 ... 116.66666667 113.66666667
  111.33333333]
 [124.33333333 104.66666667  97.66666667 ... 116.66666667 113.66666667
  111.66666667]
 [122.33333333 102.66666667  94.66666667 ... 118.33333333 115.33333333
  113.33333333]]


107.66666666666667

In [25]:
import matplotlib.image as mpimg
import numpy as np
img = mpimg.imread('/content/dog.jpeg')
gray_img_01 = 0.21 * img[:,:,0] + 0.72 * img[:,:,1] + 0.07 * img[:,:,2]
print(gray_img_01)

gray_img_01[0,0]

[[126.23  97.23  90.23 ... 159.5  159.5  159.5 ]
 [127.23  97.23  91.23 ... 160.08 159.5  160.08]
 [127.23  98.23  91.23 ... 160.01 159.08 159.01]
 ...
 [148.63 129.49 124.37 ... 139.54 136.54 134.33]
 [141.63 122.49 117.44 ... 138.89 135.89 134.4 ]
 [139.63 120.49 114.44 ... 140.03 137.03 135.54]]


126.22999999999999

In [39]:
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
import pandas as pd
df = pd.read_csv('/content/advertising.csv')
data = df.to_numpy()
print(data)

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 15.2MB/s]
[[230.1  37.8  69.2  22.1]
 [ 44.5  39.3  45.1  10.4]
 [ 17.2  45.9  69.3  12. ]
 [151.5  41.3  58.5  16.5]
 [180.8  10.8  58.4  17.9]
 [  8.7  48.9  75.    7.2]
 [ 57.5  32.8  23.5  11.8]
 [120.2  19.6  11.6  13.2]
 [  8.6   2.1   1.    4.8]
 [199.8   2.6  21.2  15.6]
 [ 66.1   5.8  24.2  12.6]
 [214.7  24.    4.   17.4]
 [ 23.8  35.1  65.9   9.2]
 [ 97.5   7.6   7.2  13.7]
 [204.1  32.9  46.   19. ]
 [195.4  47.7  52.9  22.4]
 [ 67.8  36.6 114.   12.5]
 [281.4  39.6  55.8  24.4]
 [ 69.2  20.5  18.3  11.3]
 [147.3  23.9  19.1  14.6]
 [218.4  27.7  53.4  18. ]
 [237.4   5.1  23.5  17.5]
 [ 13.2  15.9  49.6   5.6]
 [228.3  16.9  26.2  20.5]
 [ 62.3  12.6  18.3   9.7]
 [262.9   3.5  19.5  17. ]
 [142.9  29.3  12.6  15. ]
 [240.1  16.7  22.9  20.9]
 [248.8  27.1  22.9  18.9]
 [ 70.6  16.   40.8  10.5]
 [292.9  28.3  43.2  21.4]
 [112.9

In [53]:

column_4 = data[:, 3]
max_value = np.max(column_4)
print(max_value)
for index, value in enumerate(column_4):
    if value == max_value:
        max_index = index
        break
print(max_index)
mean_tv = np.mean(data[:, 0])
print(mean_tv)

banghi = np.sum(data[:,3]>=20)
print(banghi)

#cột sale >=15
filtered_data = data[data[:, 3] >= 15]
#tính giá trị trung bình dựa trên filtered
mean_sale = np.mean(filtered_data[:, 1])
print(mean_sale)

mean_newspaper = np.mean(data[:, 2])
filtered_data = data[data[:, 2] > mean_newspaper]
sum_sales = np.sum(filtered_data[:, 3])
print(sum_sales)
mean_sales = np.mean(data[:, 3])
scores = np.array(["Good" if value > mean_sales else "Bad" if value < mean_sales else "Average" for value in data[:, 3]])
print(scores[7:10])

mean_sales = np.mean(data[:, 3])
A = data[:, 3][np.abs(data[:, 3] - mean_sales).argmin()]
scores = np.array(["Good" if value > A else "Bad" if value < A else "Average" for value in data[:, 3]])
print(scores[7:10])


27.0
175
147.0425
40
26.22293577981651
1405.1
['Bad' 'Bad' 'Good']
['Bad' 'Bad' 'Good']
